### ISSUE TITLE
에어드랍 페이지 수정사항

### ISSUE THREAD

**Issue by spock-mark1** [DAIOSFoundation/nxdf_airdrop#1]
![image](https://user-images.githubusercontent.com/18748215/147916236-ae6319d0-7857-4796-bd1a-72772d3af278.png)

모바일경우에 "Connect to a wallet" 부분을 wallet address를 직접입력할 수 있도록 변경해 주세요.
solana wallet address의 validation이 필요합니다.

https://solana-labs.github.io/solana-web3.js/classes/PublicKey.html#isOnCurve
참고하여 address의 valid 확인이 가능한 것으로 보입니다.

**Comment by tonythefreedom** [comment]
지금 5K More Bonus 로 되어 있는 부분을 Max 5K 로 바꿔야 합니다. 요고도 바로 수정해서 반영 부탁 드립니다. @DooDoo11 @spock-mark1

**Comment by PaDuckk** [comment]
이슈 작업해서 마스터에 머지하였습니다.

**Comment by DooDoo11** [comment]
이슈 수정 완료하였습니다.

**Comment by spock-mark1** [comment]
![image](https://user-images.githubusercontent.com/18748215/148066258-87c29f0d-c0b2-460f-8255-47bf68633ab3.png)

이 부분 링크와 facebook을 텔레그램으로 변경 요청합니다.
감사합니다!

**Comment by DooDoo11** [comment]
![image](https://user-images.githubusercontent.com/94452089/148067919-1c0a5c54-b46f-4fa9-96f7-9010de6ef01e.png)

@tonythefreedom @spock-mark1  결과 페이지 문구도 바뀌어야할것같습니다.

**Comment by DooDoo11** [comment]
> ![image](https://user-images.githubusercontent.com/18748215/148066258-87c29f0d-c0b2-460f-8255-47bf68633ab3.png)
> 
> 이 부분 링크와 facebook을 텔레그램으로 변경 요청합니다. 감사합니다!

링크는 전부 연결해두었고 로고만 주시면 교체하겠습니다.

**Comment by lamknh** [comment]
![image](https://user-images.githubusercontent.com/54229039/148386071-6ce78fe0-23b7-40c0-b4c7-7b9b606ff38b.png)
오른쪽 노란색 버튼 스타일 MAX 5K 가운데 정렬로 수정 부탁드립니다.

**Comment by DooDoo11** [comment]
@lamknh 혹시 오류나는 상황에 대해서 내용 추가해주실수있나요??

기기, 브라우저 종류,  PC라면 화면크기 이정도만 알려주시면 감사하겠습니다!

**Comment by lamknh** [comment]
@DooDoo11 현재 맥북 프로 13, 크롬 사용중입니다! 토니님 쪽에서도 동일하게 보여서 참고해주시면 좋을 것 같습니다!

**Comment by spock-mark1** [comment]
![Screenshot_20220106-222023_Chrome.jpg](https://user-images.githubusercontent.com/18748215/148389057-1bb4a069-f985-427e-8d70-fc0965d20630.jpg)

이 얼럿은 삭제하는게 어떨까요?
모바일에서 처음 페이지로드 될 때 나옵니다.

**Comment by DooDoo11** [comment]
@lamknh 수정햇습니다!

**Comment by DooDoo11** [comment]
@spock-mark1 수정해서 배포했습니다!

**Comment by spock-mark1** [comment]
감사합니다. 그리고 디자인팀에서 텔레그램 아이콘을 제플린에 추가하셨다고 합니다. 적용 부탁드립니다.

**Comment by DooDoo11** [comment]
@spock-mark1 확인해보니 아직 제플린엔 페이스북으로되어있습니다!

**Comment by spock-mark1** [comment]
재요청하겠습니다

**Comment by spock-mark1** [comment]
![Telegram-logo.png](https://user-images.githubusercontent.com/18748215/148397871-74c9f77b-17d4-4683-b26b-c826f0310922.png)

혹시 이거로 될까요?

**Comment by DooDoo11** [comment]
넵 수정했습니다!

**Comment by spock-mark1** [comment]
감사합니다!
